/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.commerce.order.service.common.messaging.kafka.model;
@org.apache.avro.specific.AvroGenerated
public enum InventoryStatus implements org.apache.avro.generic.GenericEnumSymbol<InventoryStatus> {
  AVAILABLE, NON_AVAILABLE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"InventoryStatus\",\"namespace\":\"com.commerce.order.service.common.messaging.kafka.model\",\"symbols\":[\"AVAILABLE\",\"NON_AVAILABLE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
