server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      fail-fast: true
      server:
        default-label: main
        git:
          uri: https://github.com/MeliksahSelvi/commerce-config
          username: MeliksahSelvi
          password: ENC(Q0v/7ptKdUjtGfs2C0ZxRA+DsuzggjLMISOQxoV/jwDuQC5dFlhbH8kaJdHkr2Ac6CEpY6+2Wx/Omo1WG+X+Incsy9JwbliLraF7bdXDthg=)
          clone-on-start: true
